### ISSUE TITLE
how is the search done in each method?

### ISSUE THREAD

**Issue by ntaraujo** [jesuscc1993/querybot#5]
First off, great bot!

I see different results from `!qb s`, `!qb search` and `!go` (google.com)

I wonder why

**Comment by jesuscc1993** [comment]
`s` is just an alias for `search` so `!qb s` and `!qb search` will always return the same results.
Example: `!qb search Anila` equals [https://www.google.com/search?q=Anila](https://www.google.com/search?q=Anila)

Keyword searching, on the other hand, will only show results for a certain site.
For instance: `!gbf Anila`, where keyword `gbf` equals `gbf.wiki`, results in [https://www.google.com/search?q=site:gbf.wiki%20Anila](https://www.google.com/search?q=site:gbf.wiki%20Anila)

**Comment by ntaraujo** [comment]
Thanks for the response

but I can confirm they are not the same

![image](https://user-images.githubusercontent.com/66187211/114801152-87ca9d00-9d71-11eb-9bba-d09aa6f68366.png)

![image](https://user-images.githubusercontent.com/66187211/114801353-ec85f780-9d71-11eb-81fc-e3017e8d78d9.png)

![image](https://user-images.githubusercontent.com/66187211/114801491-2820c180-9d72-11eb-8660-8695000b959f.png)

**Comment by jesuscc1993** [comment]
I can see that you're right, but I'm afraid I don't now why at this time.
As you can see in the code, both really are bound to the same function:
```js
  s: this.mapCommand(query),
  search: this.mapCommand(query),
```
source: [https://github.com/jesuscc1993/querybot/blob/master/src/modules/core/query-bot.ts](https://github.com/jesuscc1993/querybot/blob/master/src/modules/core/query-bot.ts)

I will have to debug to see why this is happening, I opened a bug (#6) to look into it.

**Comment by jesuscc1993** [comment]
`!qb search` and  `!qb s` should now return the same results.
See #6 for details.
